### ISSUE TITLE
Request: An alternative to playwrite

### ISSUE THREAD

**Issue by cassolmedia** [stitionai/devika#127]
I tried to test this out and after installing all the dependencies and many gbs of data, I find I cannot use it because playwright doesn't support fedora (and likely never will given the maintainers replies to similar questions). Would be nice to not be hamstrung by that one package.

**Comment by Jmzp** [comment]
Same here

**Comment by kjozsa** [comment]
same story with Arch Linux. Playwright only seem to support debian-based distros..

**Comment by revan1611** [comment]
Anyone found a wrokaround?

**Comment by demanuPL** [comment]
Not working with opensuse too

**Comment by revan1611** [comment]
The only way I could workaround this was using `distrobox` with `buddybox`. Created Ubuntu container and everything works perfect now.

**Comment by bbhandari064** [comment]
I get the error below when i execute bun run start
error during build:
[commonjs--resolver] Failed to resolve entry for package "mode-watcher". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "mode-watcher" package
    at packageEntryFailure (/Users/bibekbhandari/devika/ui/node_modules/vite/dist/node/chunks/dep-Bsx9IwL8.js:12218:36)
    at resolvePackageEntry (/Users/bibekbhandari/devika/ui/node_modules/vite/dist/node/chunks/dep-Bsx9IwL8.js:12213:3)
    at tryNodeResolve (/Users/bibekbhandari/devika/ui/node_modules/vite/dist/node/chunks/dep-Bsx9IwL8.js:12116:17)
    at resolveId (/Users/bibekbhandari/devika/ui/node_modules/vite/dist/node/chunks/dep-Bsx9IwL8.js:11955:15)
    at resolveId (/Users/bibekbhandari/devika/ui/node_modules/vite/dist/node/chunks/dep-Bsx9IwL8.js:11871:23)
    at <anonymous> (/Users/bibekbhandari/devika/ui/node_modules/rollup/dist/es/shared/node-entry.js:22288:40)
    at processTicksAndRejections (native:7:39)
error: script "start" exited with code 1

can anyone help?
