### ISSUE TITLE
Runtime Error when running python devika.py: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### ISSUE THREAD

**Issue by Zandiexoder** [stitionai/devika#151]
Error code given when running: python devika.py

```
Traceback (most recent call last):
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\transformers\utils\import_utils.py", line 1390, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\transformers\pipelines\__init__.py", line 26, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\transformers\image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\transformers\image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\__init__.py", line 45, in <module>
    from tensorflow.python.feature_column import feature_column_lib as feature_column
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\feature_column\feature_column_lib.py", line 18, in <module>
    from tensorflow.python.feature_column.feature_column import *
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\feature_column\feature_column.py", line 143, in <module>
    from tensorflow.python.layers import base
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\layers\base.py", line 16, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\models.py", line 20, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\metrics.py", line 34, in <module>
    from tensorflow.python.keras import activations
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\activations.py", line 18, in <module>
    from tensorflow.python.keras.layers import advanced_activations
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\layers\__init__.py", line 22, in <module>
    from tensorflow.python.keras.engine.input_layer import Input
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\engine\input_layer.py", line 24, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\engine\base_layer.py", line 48, in <module>
    from tensorflow.python.keras.engine import base_layer_utils
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\engine\base_layer_utils.py", line 31, in <module>
    from tensorflow.python.keras.utils import tf_utils
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 22, in <module>
    from tensorflow.python.distribute.coordinator import cluster_coordinator as coordinator_lib
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\coordinator\cluster_coordinator.py", line 30, in <module>
    from tensorflow.python.distribute import parameter_server_strategy_v2
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\parameter_server_strategy_v2.py", line 31, in <module>
    from tensorflow.python.distribute import parameter_server_strategy
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\parameter_server_strategy.py", line 31, in <module>
    from tensorflow.python.distribute.cluster_resolver import SimpleClusterResolver
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\cluster_resolver\__init__.py", line 27, in <module>
    from tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver import GCEClusterResolver
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\cluster_resolver\gce_cluster_resolver.py", line 24, in <module>
    from googleapiclient import discovery  # pylint: disable=g-import-not-at-top
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\googleapiclient\discovery.py", line 57, in <module>
    from googleapiclient import _auth, mimeparse
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\googleapiclient\_auth.py", line 34, in <module>
    import oauth2client.client
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\oauth2client\client.py", line 45, in <module>
    from oauth2client import crypt
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\oauth2client\crypt.py", line 45, in <module>
    from oauth2client import _openssl_crypt
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\oauth2client\_openssl_crypt.py", line 16, in <module>
    from OpenSSL import crypto
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\OpenSSL\SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\OpenSSL\crypto.py", line 1623, in <module>
    class X509StoreFlags:
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\OpenSSL\crypto.py", line 1642, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alexa\Downloads\devika\devika.py", line 16, in <module>
    from src.agents import Agent
  File "C:\Users\alexa\Downloads\devika\src\agents\__init__.py", line 1, in <module>
    from .agent import Agent
  File "C:\Users\alexa\Downloads\devika\src\agents\agent.py", line 18, in <module>
    from src.bert.sentence import SentenceBert
  File "C:\Users\alexa\Downloads\devika\src\bert\sentence.py", line 1, in <module>
    from keybert import KeyBERT
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\keybert\__init__.py", line 2, in <module>
    from keybert._model import KeyBERT
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\keybert\_model.py", line 17, in <module>
    from keybert.llm._base import BaseLLM
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\keybert\llm\__init__.py", line 7, in <module>
    from keybert.llm._textgeneration import TextGeneration
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\keybert\llm\_textgeneration.py", line 2, in <module>
    from transformers import pipeline, set_seed
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\transformers\utils\import_utils.py", line 1380, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\transformers\utils\import_utils.py", line 1392, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

**Comment by pichenka19** [comment]
File "C:\Users\alexa\AppData\Roaming\Python\Python310\site-packages\transformers\utils\import_utils.py", line 1380, in __getattr__ - done with it, please be patient next time codding
