### ISSUE TITLE
not found css file; sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by An-Jhon** [stitionai/devika#188]
# 1、the terminal of `bun run dev` got the issue:
```
SvelteKitError: Not found: /css/modules/laydate/default/laydate.css
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /css/modules/layer/default/layer.css
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /css/modules/code.css
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /css/modules/laydate/default/laydate.css
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /css/modules/layer/default/layer.css
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /css/modules/code.css
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/Users/ayd/Desktop/Project_practice/Devika/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```

# 2、the terminal of `python3 devika.py` got the problem:
```
[2024-03-27 17:48:00,966] ERROR in app: Exception on /api/token-usage [GET]
Traceback (most recent call last):
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
    return self.pool.connect()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ayd/Desktop/Project_practice/Devika/devika/src/logger.py", line 58, in wrapper
    response = func(*args, **kwargs)
  File "/Users/ayd/Desktop/Project_practice/Devika/devika/devika.py", line 164, in token_usage
    token_count = AgentState().get_latest_token_usage(project_name)
  File "/Users/ayd/Desktop/Project_practice/Devika/devika/src/state.py", line 20, in __init__
    SQLModel.metadata.create_all(self.engine)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 5825, in create_all
    bind._run_ddl_visitor(
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3254, in _run_ddl_visitor
    with self.begin() as conn:
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3244, in begin
    with self.connect() as conn:
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in connect
    return self._connection_cls(self)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2444, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
    return self.pool.connect()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/ayd/miniconda3/envs/ollama/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by ARajgor** [comment]
fetch the latest changes.
