### ISSUE TITLE
Groq.__init__() missing 1 required positional argument: 'api_key'

### ISSUE THREAD

**Issue by breax1** [stitionai/devika#192]
Groq is unavailable. There is no response over the interface, when I send a query with Postman I get the following error.

24.03.27 14:50:23: root: INFO   : /api/execute-agent POST
24.03.27 14:50:23: root: DEBUG  : /api/execute-agent POST - Response: {"message":"Started Devika Agent"}

project='test' state_stack_json='[{"internal_monologue": null, "browser_session": {"url": null, "screenshot": null}, "terminal_session": {"command": null, "output": null, "title": null}, "step": null, "message": null, "completed": false, "agent_is_active": true, "token_usage": 7427, "timestamp": "2024-03-27 08:14:22"}]' id=1
Exception in thread Thread-650 (<lambda>):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/breax/devike1/devika/devika.py", line 52, in <lambda>
    target=lambda: Agent(base_model=base_model).execute(prompt, project_name)
  File "/home/breax/devike1/devika/src/agents/agent.py", line 266, in execute
    plan = self.planner.execute(prompt, project_name_from_user)
  File "/home/breax/devike1/devika/src/agents/planner/planner.py", line 70, in execute
    response = self.llm.inference(prompt, project_name)
  File "/home/breax/devike1/devika/src/llm/llm.py", line 74, in inference
    response = Groq().inference(self.model_id, prompt).strip()
TypeError: Groq.__init__() missing 1 required positional argument: 'api_key'

**Comment by mufeedvh** [comment]
Fixed in #193, thanks! 🙌
