### ISSUE TITLE
use RELEASE publish full working code e.g. release 1.0.2

### ISSUE THREAD

**Issue by tikendraw** [stitionai/devika#228]
i have been tryiing to use it. got this error
```
 python3 devika.py 
Traceback (most recent call last):
  File "/home/t/atest/devika/devika.py", line 16, in <module>
    from src.agents import Agent
  File "/home/t/atest/devika/src/agents/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/home/t/atest/devika/src/agents/agent.py", line 1, in <module>
    from .planner import Planner
  File "/home/t/atest/devika/src/agents/planner/__init__.py", line 1, in <module>
    from .planner import Planner
  File "/home/t/atest/devika/src/agents/planner/planner.py", line 3, in <module>
    from src.llm import LLM
  File "/home/t/atest/devika/src/llm/__init__.py", line 1, in <module>
    from .llm import LLM
  File "/home/t/atest/devika/src/llm/llm.py", line 4, in <module>
    from .ollama_client import Ollama
  File "/home/t/atest/devika/src/llm/ollama_client.py", line 7, in <module>
    logger = Logger()
             ^^^^^^^^
  File "/home/t/atest/devika/src/logger.py", line 10, in __init__
    config = Config()
             ^^^^^^^^
  File "/home/t/atest/devika/src/config.py", line 11, in __new__
    cls._instance.config = toml.load("config.toml")
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t/atest/devika/.venv/lib/python3.11/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.toml'

```

I did not try to fix it. My request is  release fully working and tested versions of the code as release x.x.x . so that people use working releases rather than evolving branches. do `Releases`.

**Comment by Guerdal** [comment]
It's normal, https://github.com/stitionai/devika/pull/197 replace it by sample.config.toml. You need to copy that file to config.toml and modify it with the good informations

**Comment by power9799** [comment]
> It's normal, #197 replace it by sample.config.toml. You need to copy that file to config.toml and modify it with the good informations

How do you do that?

**Comment by shanujha** [comment]
copy the file `sample.config.toml` in the same directory. Now rename this new file to config.toml
Make sure you still have 2 files
`sample.config.toml` and `config.toml` 
Now you can continue to add your api keys, etc in the `config.toml`.

Hereafter, *DO NOT TOUCH OR DELETE* `sample.config.toml`, as it is a safeguard from preventing anyone to push their secret keys on github, especially since this is public repository/fork

Please close issue if solved!

**Comment by tikendraw** [comment]
# DO VERSION RELEASE
# DON'T RECOMMEND EVOLVING BRANCHES
