### ISSUE TITLE
Agent stuck in "Writing Code..." after it browsed through a few pages.

### ISSUE THREAD

**Issue by Sridhar701Pitt** [stitionai/devika#244]
```
devika-backend-engine-1  | 24.03.29 11:11:15: root: INFO   : /api/get-browser-snapshot GET
devika-backend-engine-1  | 5024.03.29 11:11:15: root: EXCEPT : /api/get-browser-snapshot GET - Attempted implicit sequence conversion but the response object is in direct passthrough mode.)
devika-backend-engine-1  | Traceback (most recent call last):
devika-backend-engine-1  |   File "/home/nonroot/devika/src/logger.py", line 63, in wrapper
devika-backend-engine-1  |     response_summary = response.get_data(as_text=True)
devika-backend-engine-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
devika-backend-engine-1  |   File "/home/nonroot/devika/.venv/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 283, in get_data
devika-backend-engine-1  |     self._ensure_sequence()
devika-backend-engine-1  |   File "/home/nonroot/devika/.venv/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 331, in _ensure_sequence
devika-backend-engine-1  |     raise RuntimeError(
devika-backend-engine-1  | RuntimeError: Attempted implicit sequence conversion but the response object is in direct passthrough mode.
```

Agent stuck in "Writing Code..." after it browsed through a few pages. Not sure what the issue is.

**Comment by Sridhar701Pitt** [comment]
This issue was already referenced. So I closed this one.

Ref: https://github.com/stitionai/devika/issues/194
