### ISSUE TITLE
libcublas.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sqwotmars** [stitionai/devika#247]
Hello

Installing Devika on a Virtual Machine without a GPU. I get the error: libcublas.so.12: cannot open shared object file: No such file or directory Please tell me, is it possible to run this system exclusively on the CPU? OLLAMA was installed in exactly this mode

Thank you

**Comment by mufeedvh** [comment]
Yes, this project does not require a GPU. Please follow the [Quick Start](https://github.com/stitionai/devika?tab=readme-ov-file#quick-start) guide. Please let me know if the issue persists.

**Comment by sqwotmars** [comment]
Hello
I went through the quick start. I made a separate environment for python, loaded dependencies, launched ui. When running python3 devika.py, I still get the error: 
python3 devika.py
Traceback (most recent call last):
  File "devika.py", line 16, in <module>
    from src.agents import Agent
  File "/home/ms/devika/src/agents/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/home/ms/devika/src/agents/agent.py", line 18, in <module>
    from src.bert.sentence import SentenceBert
  File "/home/ms/devika/src/bert/sentence.py", line 1, in <module>
    from keybert import KeyBERT
  File "/usr/local/lib/python3.8/dist-packages/keybert/__init__.py", line 1, in <module>
    from keybert._llm import KeyLLM
  File "/usr/local/lib/python3.8/dist-packages/keybert/_llm.py", line 4, in <module>
    from sentence_transformers import util
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcublas.so.12: cannot open shared object file: No such file or directory
