### ISSUE TITLE
httpx.ConnectError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by NorbiXD** [stitionai/devika#27]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/norbertpapp/Desktop/devika/devika.py", line 16, in <module>
    from src.agents import Agent
  File "/Users/norbertpapp/Desktop/devika/src/agents/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/Users/norbertpapp/Desktop/devika/src/agents/agent.py", line 1, in <module>
    from .planner import Planner
  File "/Users/norbertpapp/Desktop/devika/src/agents/planner/__init__.py", line 1, in <module>
    from .planner import Planner
  File "/Users/norbertpapp/Desktop/devika/src/agents/planner/planner.py", line 3, in <module>
    from src.llm import LLM
  File "/Users/norbertpapp/Desktop/devika/src/llm/__init__.py", line 1, in <module>
    from .llm import LLM, TOKEN_USAGE
  File "/Users/norbertpapp/Desktop/devika/src/llm/llm.py", line 14, in <module>
    class Model(Enum):
  File "/Users/norbertpapp/Desktop/devika/src/llm/llm.py", line 25, in Model
    for model in Ollama.list_models()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/norbertpapp/Desktop/devika/src/llm/ollama_client.py", line 6, in list_models
    return ollama.list()["models"]
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ollama/_client.py", line 328, in list
    return self._request('GET', '/api/tags').json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ollama/_client.py", line 68, in _request
    response = self._client.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 61] Connection refused

**Comment by jasonnwn** [comment]
Same error. Tried turning off Firewalls as test and that didn't fix the issue.

**Comment by wrapss** [comment]
look this [PR](https://github.com/stitionai/devika/pull/14)

**Comment by cyberiumabc** [comment]
This hasn't fixed the issue.

**Comment by cyberiumabc** [comment]
Uh! Just figured this out. 
You need to run ollama locally before using devika dev. Go here[ https://github.com/ollama/ollama]( https://github.com/ollama/ollama)

**Comment by NorbiXD** [comment]
> look this [PR](https://github.com/stitionai/devika/pull/14)

This works

**Comment by mufeedvh** [comment]
Ollama server is checked at runtime now, thanks for opening this issue, fixed! 🙌
