### ISSUE TITLE
OSError: Can't load the configuration of 'sentence-transformers/all-MiniLM-L6-v2'

### ISSUE THREAD

**Issue by llg0363** [stitionai/devika#293]
i pulled the newest code today, when i excute "python devika.py", i got this error 

24.04.01 20:16:34: root: INFO   : Initializing Devika...
24.04.01 20:16:34: root: INFO   : Initializing Prerequisites Jobs...
24.04.01 20:16:37: root: INFO   : Loading sentence-transformer BERT models...
No sentence-transformers model found with name sentence-transformers/all-MiniLM-L6-v2. Creating a new one with MEAN pooling.
Traceback (most recent call last):
  File "~/devika/.venv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "~/devika/.venv/lib/python3.9/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "~/devika/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "~/devika/.venv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "~/devika/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "~/devika/.venv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "~/devika/.venv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "~/devika/.venv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 392, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "~/devika/.venv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "~/devika/.venv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "~/devika/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 68, in send
    return super().send(request, *args, **kwargs)
  File "~/devika/.venv/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "~/devika/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 779, in urlopen
    self._prepare_proxy(conn)
  File "~/devika/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1048, in _prepare_proxy
    conn.connect()
  File "~/devika/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "~/devika/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "~/devika/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "~/devika/.venv/lib/python3.9/site-packages/eventlet/greenio/base.py", line 261, in connect
    self._trampoline(fd, write=True, timeout=timeout, timeout_exc=_timeout_exc)
  File "~/devika/.venv/lib/python3.9/site-packages/eventlet/greenio/base.py", line 206, in _trampoline
    return trampoline(fd, read=read, write=write, timeout=timeout,
  File "~/devika/.venv/lib/python3.9/site-packages/eventlet/hubs/__init__.py", line 155, in trampoline
    listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
  File "~/devika/.venv/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 52, in add
    self._control([event], 0, 0)
  File "~/devika/.venv/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 38, in _control
    return self.kqueue.control(events, max_events, timeout)
TypeError: changelist must be an iterable of select.kevent objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/devika/devika.py", line 8, in <module>
    init_devika()
  File "~/devika/src/init.py", line 28, in init_devika
    SentenceBert(prompt).extract_keywords()
  File "~/devika/src/bert/sentence.py", line 6, in __init__
    self.kw_model = KeyBERT()
  File "~/devika/.venv/lib/python3.9/site-packages/keybert/_model.py", line 57, in __init__
    self.model = select_backend(model)
  File "~/devika/.venv/lib/python3.9/site-packages/keybert/backend/_utils.py", line 48, in select_backend
    return SentenceTransformerBackend(embedding_model)
  File "~/devika/.venv/lib/python3.9/site-packages/keybert/backend/_sentencetransformers.py", line 42, in __init__
    self.embedding_model = SentenceTransformer(embedding_model)
  File "~/devika/.venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 199, in __init__
    modules = self._load_auto_model(
  File "~/devika/.venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 1134, in _load_auto_model
    transformer_model = Transformer(
  File "~/devika/.venv/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 35, in __init__
    config = AutoConfig.from_pretrained(model_name_or_path, **model_args, cache_dir=cache_dir)
  File "~/devika/.venv/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "~/devika/.venv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "~/devika/.venv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 707, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'sentence-transformers/all-MiniLM-L6-v2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'sentence-transformers/all-MiniLM-L6-v2' is the correct path to a directory containing a config.json file

befor i pulled the code, this project is functional, how can i resove this problem? btw, the fronend service is functional, i can browser in chrome, network seems no problem.

**Comment by sun54907** [comment]
I met same problem. and solved it.

I found this stackoverflow.
https://stackoverflow.com/questions/78001556/error-while-installing-sentence-transformers

> You need to use python 3.11 to install sentence-transformers

Try "python3 devika.py".

If same error exists, upgrade python3, and go through the installation process on README step by step.

**Comment by llg0363** [comment]
upgrade my python version to 3.12 and resolved this issue.thanks for replay.

**Comment by codesyco** [comment]
help i have this issues as well, i tried upgrading to python 3.12 but that didn't work, i also tried the python3 but it didn't work it says python3 is not recognized
