### ISSUE TITLE
Python Service Exception: Using Playwright Sync API inside the asyncio loop

### ISSUE THREAD

**Issue by harun-prasad** [stitionai/devika#316]
**Describe the bug**
The below execption was thrown in Python
Exception in thread Thread-8 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\harun\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\harun\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\source_code\other\devika\devika.py", line 94, in <lambda>
    thread = Thread(target=lambda: agent.execute(message, project_name, search_engine))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source_code\other\devika\src\agents\agent.py", line 337, in execute
    search_results = self.search_queries(queries, project_name, engine)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source_code\other\devika\src\agents\agent.py", line 83, in search_queries
    browser = Browser()
              ^^^^^^^^^
  File "D:\source_code\other\devika\src\browser\browser.py", line 13, in __init__
    self.playwright = sync_playwright().start()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source_code\other\devika\.venv\Lib\site-packages\playwright\sync_api\_context_manager.py", line 85, in start
    return self.__enter__()
           ^^^^^^^^^^^^^^^^
  File "D:\source_code\other\devika\.venv\Lib\site-packages\playwright\sync_api\_context_manager.py", line 48, in __enter__
    raise Error(
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

**To Reproduce**
Simply asked Devika to create "python script to print hello world". When devika was trying to browse the internet and get a screnshot of the page, this error was thrown. I am using DuckDuckGo for search engine and Mistral 7b as the model.

**Expected behavior**
NA

**Screenshots**
![image](https://github.com/stitionai/devika/assets/57983063/7e366fee-9ab0-47a0-baec-c0dc137b4224)
**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11 22H2
 - Browser Edge Browser
 - Version Version 123.0.2420.65 (Official build) (64-bit)

**Additional context**

**Comment by harun-prasad** [comment]
@Polygons1  Thanks. This issue is fixed in https://github.com/stitionai/devika/pull/298
