### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by siddharthd0** [stitionai/devika#32]
Device:
Macbook Air 2017

Error:
(base) MacBook-Pro-207:devika siddharthduggal$ python devika.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/opt/anaconda3/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/opt/anaconda3/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/opt/anaconda3/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/opt/anaconda3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/siddharthduggal/Desktop/devika/devika.py", line 16, in <module>
    from src.agents import Agent
  File "/Users/siddharthduggal/Desktop/devika/src/agents/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/Users/siddharthduggal/Desktop/devika/src/agents/agent.py", line 1, in <module>
    from .planner import Planner
  File "/Users/siddharthduggal/Desktop/devika/src/agents/planner/__init__.py", line 1, in <module>
    from .planner import Planner
  File "/Users/siddharthduggal/Desktop/devika/src/agents/planner/planner.py", line 3, in <module>
    from src.llm import LLM
  File "/Users/siddharthduggal/Desktop/devika/src/llm/__init__.py", line 1, in <module>
    from .llm import LLM, TOKEN_USAGE
  File "/Users/siddharthduggal/Desktop/devika/src/llm/llm.py", line 14, in <module>
    class Model(Enum):
  File "/Users/siddharthduggal/Desktop/devika/src/llm/llm.py", line 25, in Model
    for model in Ollama.list_models()
  File "/Users/siddharthduggal/Desktop/devika/src/llm/ollama_client.py", line 6, in list_models
    return ollama.list()["models"]
  File "/opt/anaconda3/lib/python3.9/site-packages/ollama/_client.py", line 328, in list
    return self._request('GET', '/api/tags').json()
  File "/opt/anaconda3/lib/python3.9/site-packages/ollama/_client.py", line 68, in _request
    response = self._client.request(method, url, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/anaconda3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/anaconda3/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 61] Connection refused
^[(base) MacBook-Pro-207:devika siddharthduggal$

**Comment by cyberiumabc** [comment]
Try this. https://github.com/stitionai/devika/issues/27#issuecomment-2014158508
