### ISSUE TITLE
SvelteKitError: Not found: /sw.js

### ISSUE THREAD

**Issue by Nic-Raf** [stitionai/devika#327]
I've installed devika properly or is there something missing?

VITE v5.2.8  ready in 1074 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
SvelteKitError: Not found: /sw.js
    at resolve (E:\AI_Softwares\devika\ui\node_modules\@sveltejs\kit\src\runtime\server\respond.js:522:13)
    at resolve (E:\AI_Softwares\devika\ui\node_modules\@sveltejs\kit\src\runtime\server\respond.js:322:5)
    at #options.hooks.handle (E:\AI_Softwares\devika\ui\node_modules\@sveltejs\kit\src\runtime\server\index.js:71:56)
    at Module.respond (E:\AI_Softwares\devika\ui\node_modules\@sveltejs\kit\src\runtime\server\respond.js:319:40) {
  status: 404,
  text: 'Not Found'
}

**Comment by ARajgor** [comment]
node version?

**Comment by Falkonar** [comment]
> node version?

 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,

**Comment by ARajgor** [comment]
I mean which node js version do you use?

**Comment by Falkonar** [comment]
> I mean which node js version do you use?

v20.10.0

**Comment by ARajgor** [comment]
Clean install and tell if the issue is persist.

**Comment by Falkonar** [comment]
> Clean install and tell if the issue is persist.

I run it on linux. Give up with winfows

**Comment by shooflyshoo** [comment]
I'm getting this issue on Mac OS via Pinokio install. 
![Screenshot 2024-04-18 at 9 59 43 AM](https://github.com/stitionai/devika/assets/876389/c27d3718-57fb-480e-af9b-4a022d6cc663)

**Comment by ARajgor** [comment]
> I'm getting this issue on Mac OS via Pinokio install. 
> ![Screenshot 2024-04-18 at 9 59 43 AM](https://github.com/stitionai/devika/assets/876389/c27d3718-57fb-480e-af9b-4a022d6cc663)
> 

You are using old version. Fetch the latest changes and clean install it.

**Comment by ARajgor** [comment]
this is issue is regarding older versions of dependencies and node versions. upgrade node > 18 or 20 is recommended.
