### ISSUE TITLE
Error: Cannot find module @rollup/rollup-darwin-x64

### ISSUE THREAD

**Issue by jonatas** [stitionai/devika#351]
**Describe the bug**

Trying to follow the steps on MacOs I cannot make it work.

**To Reproduce**

Steps to reproduce the behavior occur during the bun install:

```bash
bun install
bun install v1.1.0 (5903a614)
  ⚙️  @sveltejs/kit [1/2] /Users/jonatasdp/code/devika/ui/node_modules/rollup/dist/native.js:87
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory. bun install
bun install v1.1.0 (5903a614)
  ⚙️  @sveltejs/kit [1/2] /Users/jonatasdp/code/devika/ui/node_modules/rollup/dist/native.js:87
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/jonatasdp/code/devika/ui/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/Users/jonatasdp/code/devika/ui/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-x64'
  ```
  
  
  Additional context:
  ```
  OS: MacOs M1 2020 - Sonoma 14.1.1
  python --version => Python 3.9.10
(devika) jonatasdp@~/code/devika/ui node --version
v20.11.1
  ```

**Comment by jonatas** [comment]
fixed by doing `npm i @rollup/rollup-darwin-x64` directly.
