### ISSUE TITLE
Error while connecting Gemini

### ISSUE THREAD

**Issue by dhan-kum** [stitionai/devika#371]
Post connection to GEMINI getting below error. I have done the set-up on Windows. What could be the reason of having below error?

24.04.05 14:10:36: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'Please tell me how many days in a week?', 'timestamp': '2024-04-05 14:10:36'}}
24.04.05 14:10:36: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 742}
Model: gemini-pro, Enum: GOOGLE
E0405 14:10:38.675000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:38.675000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:39.324000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:39.324000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:40.503000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:40.503000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:40.923000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:40.923000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:41.628000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:41.628000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:43.347000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:43.348000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:46.623000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:46.623000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:51.029000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:51.029000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:10:54.043000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:10:54.043000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:00.046000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:00.047000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:08.578000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:08.579000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:10.858000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:10.859000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:11.264000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:11.264000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:18.104000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:18.104000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:19.556000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:19.556000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:27.730000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:27.730000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
E0405 14:11:33.224000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:85] validate_metadata_from_plugin: INTERNAL:Illegal header value
E0405 14:11:33.225000000 15940 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] Plugin added invalid metadata value.
Exception in thread Thread-3 (<lambda>):
Traceback (most recent call last):
  File "C:\Work\Mo4D\Devika\devika\.venv\Lib\site-packages\google\api_core\grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\Mo4D\Devika\devika\.venv\Lib\site-packages\grpc\_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\Mo4D\Devika\devika\.venv\Lib\site-packages\grpc\_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable

**Comment by nullnuller** [comment]
On a related topic, how to add more gemini models (or fot that matter more Open AI) to the selector?

![image](https://github.com/stitionai/devika/assets/32858321/aa75145c-f77b-4173-bf4d-98d7176c7a17)

**Comment by Preet-Sojitra** [comment]
Facing same error. Any solutions to fix it?\\

**Comment by foudil-lw** [comment]
@pnikonowicz I love you! ❤️ 
The issue was indeed a trailing `\n` (`0xa0`) in the secret. Generally applicable to GCP secrets, not specific to *devika*.
