### ISSUE TITLE
issue with bun config "ReferenceError: Request is not defined"

### ISSUE THREAD

**Issue by saikethan27** [stitionai/devika#403]
ReferenceError: Request is not defined
    at getRequest (file:///C:/Users/madha/devika/ui/node_modules/@sveltejs/kit/src/exports/node/index.js:107:2)
    at file:///C:/Users/madha/devika/ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
    
    
![image](https://github.com/stitionai/devika/assets/64608068/eec89b17-f58c-4802-bb08-7b87b191e3c3)

**Comment by lookatitude** [comment]
same

**Comment by ARajgor** [comment]
node version??

**Comment by lookatitude** [comment]
> node version??

Was using node v16, updated to v21 and its working.

**Comment by ARajgor** [comment]
minimum requirements of node > 18

**Comment by wesleyscholl** [comment]
If you see this when running `bun run start`:

```
error during build:
TypeError: layouts.at is not a function
    at file:///Users/wscholl/devikatest/devika/ui/node_modules/@sveltejs/kit/src/core/sync/write_client_manifest.js:62:22
    at Array.map (<anonymous>)
    at write_client_manifest (file:///Users/wscholl/devikatest/devika/ui/node_modules/@sveltejs/kit/src/core/sync/write_client_manifest.js:57:6)
    at create (file:///Users/wscholl/devikatest/devika/ui/node_modules/@sveltejs/kit/src/core/sync/sync.js:31:2)
    at Module.all (file:///Users/wscholl/devikatest/devika/ui/node_modules/@sveltejs/kit/src/core/sync/sync.js:58:9)
    at config (file:///Users/wscholl/devikatest/devika/ui/node_modules/@sveltejs/kit/src/exports/vite/index.js:325:27)
    at runConfigHook (file:///Users/wscholl/devikatest/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:70001:31)
    at async resolveConfig (file:///Users/wscholl/devikatest/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:69449:14)
    at async build (file:///Users/wscholl/devikatest/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:68534:20)
    at async CAC.<anonymous> (file:///Users/wscholl/devikatest/devika/ui/node_modules/vite/dist/node/cli.js:842:9)
error: script "start" exited with code 1
```

Upgrade your node version to 18 or higher.

**Comment by TYeniyayla** [comment]
I get the same life. node -v output:
v22.9.0
