### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'index'

### ISSUE THREAD

**Issue by NinjaEde** [stitionai/devika#430]
On a new project, I used **DuckDuckGo** as search engine and **Ollama/Llama2** as LLM

After I gave the prompt to Devika it starts normal and was corresponding with my local LLM. 
It also had a query for me, which I answered and it processed to the next step afterwards.

When it came to "Browsing the web"
the following error occurs and it stopped processing:

![image](https://github.com/stitionai/devika/assets/8362096/ec2c0858-ea21-4bcf-a733-31198c52c927)

**Comment by ARajgor** [comment]
how to reproduce the error??

**Comment by stevie86** [comment]
happened to me too today!
`24.04.15 19:10:23: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":"Hum, interesting approach! Using SQLAlchemy for cross-platform compatibility sounds like a robust choice. Time to delve into those library options and see what fits best.","message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-15 19:09:48","token_usage":966}}

24.04.15 19:10:23: root: INFO   : /api/get-agent-state POST
24.04.15 19:10:23: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":"Hum, interesting approach! Using SQLAlchemy for cross-platform compatibility sounds like a robust choice. Time to delve into those library options and see what fits best.","message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-15 19:09:48","token_usage":966}}

TimeoutError: Page.goto: Timeout 20000ms exceeded.
Call log:
navigating to "https://stackoverflow.com/questions/11157894/less-painful-way-to-parse-a-rss-feed-with-lxml", waiting until "load"
 when trying to navigate to https://stackoverflow.com/questions/11157894/less-painful-way-to-parse-a-rss-feed-with-lxml
24.04.15 19:10:44: root: INFO   : SOCKET agent-state MESSAGE: [{'internal_monologue': None, 'browser_session': {'url': None, 'screenshot': None}, 'terminal_session': {'command': None, 'output': None, 'title': None}, 'step': None, 'message': None, 'completed': False, 'agent_is_active': True, 'token_usage': 1262, 'timestamp': '2024-04-15 19:09:09'}, {'internal_monologue': 'Hum, interesting approach! Using SQLAlchemy for cross-platform compatibility sounds like a robust choice. Time to delve into those library options and see what fits best.', 'browser_session': {'url': None, 'screenshot': None}, 'terminal_session': {'command': None, 'output': None, 'title': None}, 'step': None, 'message': None, 'completed': False, 'agent_is_active': True, 'token_usage': 966, 'timestamp': '2024-04-15 19:09:48'}, {'internal_monologue': 'Browsing the web right now...', 'browser_session': {'url': 'https://stackoverflow.com/questions/11157894/less-painful-way-to-parse-a-rss-feed-with-lxml', 'screenshot': 'screenshots/734f4bc14ba5afb656d4115be5d57135bb869fcc.png'}, 'terminal_session': {'command': None, 'output': None, 'title': None}, 'step': None, 'message': None, 'completed': False, 'agent_is_active': True, 'token_usage': 0, 'timestamp': '2024-04-15 19:10:44'}]
24.04.15 19:10:44: root: INFO   : /api/get-browser-snapshot GET
24.04.15 19:10:44: root: DEBUG  : /api/get-browser-snapshot GET - Response: File response
24.04.15 19:10:44: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 2956}
Model: gemma-7b-it, Enum: GROQ
24.04.15 19:10:59: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 2098}
24.04.15 19:10:59: root: INFO   : got the search results for : python libraries for rss feed parsing: feedparser vs lxml
Exception in thread Thread-3 (<lambda>):
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/devika/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/user/miniconda3/envs/devika/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/coding/devika/devika.py", line 96, in <lambda>
    thread = Thread(target=lambda: agent.execute(message, project_name))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/coding/devika/src/agents/agent.py", line 347, in execute
    search_results = self.search_queries(queries, project_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/coding/devika/src/agents/agent.py", line 106, in search_queries
    web_search.search(query)
  File "/home/user/coding/devika/src/browser/search.py", line 133, in search
    self.duck(query)
  File "/home/user/coding/devika/src/browser/search.py", line 111, in duck
    vqd = self.extract_vqd(resp)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/coding/devika/src/browser/search.py", line 143, in extract_vqd
    start = html_bytes.index(start_pattern) + offset
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'index'
^CKeyboardInterrupt
2024-04-15T17:12:26Z
Traceback (most recent call last):
  File "/home/user/coding/devika/devika.py", line 201, in <module>
    socketio.run(app, debug=False, port=1337, host="0.0.0.0")
  File "/home/user/miniconda3/envs/devika/lib/python3.11/site-packages/flask_socketio/__init__.py", line 718, in run
    self.wsgi_server.serve_forever()
  File "/home/user/miniconda3/envs/devika/lib/python3.11/site-packages/gevent/baseserver.py", line 400, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
KeyboardInterrupt`

**Comment by golyalpha** [comment]
I don't think this has been resolved - I'm getting the same exact issue when trying to use DDG as the search engine:

```
Exception in thread Thread-3 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\golyalpha\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\golyalpha\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\golyalpha\git\devika\devika.py", line 89, in <lambda>
    thread = Thread(target=lambda: agent.execute(message, project_name))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\golyalpha\git\devika\src\agents\agent.py", line 344, in execute
    search_results = self.search_queries(queries, project_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\golyalpha\git\devika\src\agents\agent.py", line 104, in search_queries
    web_search.search(query)
  File "C:\Users\golyalpha\git\devika\src\browser\search.py", line 136, in search
    self.duck(query)
  File "C:\Users\golyalpha\git\devika\src\browser\search.py", line 114, in duck
    vqd = self.extract_vqd(resp)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\golyalpha\git\devika\src\browser\search.py", line 146, in extract_vqd
    start = html_bytes.index(start_pattern) + offset
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'index'
```
