### ISSUE TITLE
Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED])

### ISSUE THREAD

**Issue by areefskcg** [stitionai/devika#446]
Im getting SSL verification failed issue while running python devika.py. can anyone help me on this???

(devika) PS C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika> python devika.py
24.04.16 13:07:49: root: INFO   : Initializing Devika...
24.04.16 13:07:49: root: INFO   : Initializing Prerequisites Jobs...
24.04.16 13:08:02: root: INFO   : Loading sentence-transformer BERT models...
Traceback (most recent call last):
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\gevent\ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\gevent\ssl.py", line 349, in __init__
    self.do_handshake()
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\gevent\ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /sentence-transformers/all-MiniLM-L6-v2/53aa51172d142c89d9012cce15ae4d6cc0ca6895895114379cacb4fab128d9db?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1713510889&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzUxMDg4OX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=mqQxdzHtkUhAN7L~If8JLGtNKl4wzShCXvuFr1VWLvqL1lmcbpAdbD27erJtBMrpKo4yK~veAb1YJhPjFvDxT~dHCOAmzaqQoFdTmfKSUZCN7KAhbY8Nt-4NjuxAm2Zbw7blAiwGgNQ~gXcf2sLtWc-yyuekh~Iwz0EV~RcPrfO7xxdliBZ0uYKdMp2MsIFKkXfoIJDQIUzwyJa3e7~tQL0r~9s8YcOtkxvik33XT8GEO0qlacEhDyjFdQzIHOzfF0Ouv7o~K4iAo74UU3AOX9j2dG58q9qGBmGQY7EXKzd~6jBjuIoicF7tHeyipwX7oidhLXmfLEJVYud1IkKdjQ__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\devika.py", line 10, in <module>
    init_devika()
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\src\init.py", line 28, in init_devika
    SentenceBert(prompt).extract_keywords()
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\src\bert\sentence.py", line 6, in __init__
    self.kw_model = KeyBERT()
                    ^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\keybert\_model.py", line 57, in __init__
    self.model = select_backend(model)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\keybert\backend\_utils.py", line 48, in select_backend
    return SentenceTransformerBackend(embedding_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\keybert\backend\_sentencetransformers.py", line 42, in __init__
    self.embedding_model = SentenceTransformer(embedding_model)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 191, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1233, in _load_sbert_model
    module = Transformer(model_name_or_path, cache_dir=cache_folder, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\sentence_transformers\models\Transformer.py", line 36, in __init__
    self._load_model(model_name_or_path, config, cache_dir, **model_args)
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\sentence_transformers\models\Transformer.py", line 65, in _load_model
    self.auto_model = AutoModel.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3190, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 1492, in hf_hub_download
    http_get(
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 456, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\huggingface_hub\file_download.py", line 392, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\huggingface_hub\utils\_http.py", line 68, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika\.venv\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /sentence-transformers/all-MiniLM-L6-v2/53aa51172d142c89d9012cce15ae4d6cc0ca6895895114379cacb4fab128d9db?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1713510889&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzUxMDg4OX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=mqQxdzHtkUhAN7L~If8JLGtNKl4wzShCXvuFr1VWLvqL1lmcbpAdbD27erJtBMrpKo4yK~veAb1YJhPjFvDxT~dHCOAmzaqQoFdTmfKSUZCN7KAhbY8Nt-4NjuxAm2Zbw7blAiwGgNQ~gXcf2sLtWc-yyuekh~Iwz0EV~RcPrfO7xxdliBZ0uYKdMp2MsIFKkXfoIJDQIUzwyJa3e7~tQL0r~9s8YcOtkxvik33XT8GEO0qlacEhDyjFdQzIHOzfF0Ouv7o~K4iAo74UU3AOX9j2dG58q9qGBmGQY7EXKzd~6jBjuIoicF7tHeyipwX7oidhLXmfLEJVYud1IkKdjQ__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))"), '(Request ID: eda5dda5-c22a-4cb5-99ff-2881a5fc52e4)')
(devika) PS C:\Users\SAREEF\Videos\GEN-AI-WORK\devika\devika>

**Comment by tomhup** [comment]
are you use a proxy？

**Comment by areefskcg** [comment]
> are you use a proxy？

No, i've just followed the steps as mentioned in repo

**Comment by 20481A5450** [comment]
To solve the SSL Error  I would suggest installing this package
`pip install pip-system-certs
`
**Try installing this package and let me know!**

**Comment by areefskcg** [comment]
> pip install pip-system-certs

still same issue coming @20481A5450

**Comment by 20481A5450** [comment]
Ensure you have the latest version of Python and its packages installed, especially **requests** and **urllib3**. You can upgrade them using:

```bash
pip install --upgrade requests urllib3
```
Try this and let me know @areefskcg

**Comment by areefskcg** [comment]
still same issue bro @20481A5450

**Comment by ARajgor** [comment]
can you follow this https://github.com/huggingface/transformers/issues/25552.
this is not related to devika. it between your network and huggingface so closing it.
