### ISSUE TITLE
ModuleNotFoundError: No module named 'gevent'

### ISSUE THREAD

**Issue by Sai-Jahnavi-Bachu** [stitionai/devika#449]
python devika.py
Traceback (most recent call last):
  File "C:\Users\sai jahnavi\Desktop\myenv\devika\devika.py", line 7, in <module>
    from gevent import monkey
ModuleNotFoundError: No module named 'gevent'

**Comment by 20481A5450** [comment]
What was the error you're getting. @Sai-Jahnavi-Bachu

**Comment by yishin** [comment]
$ python devika.py                        
Traceback (most recent call last):
  File "/Users/chuck/ai/devika/devika.py", line 5, in <module>
    from gevent import monkey
ModuleNotFoundError: No module named 'gevent'

**Comment by yishin** [comment]
The issue has been resolved.

Cause: Python version issue
Resolution: Downgraded from v3.12 to v3.11.x
Explanation: The requirements specify that the Python version must be below 3.12. Additionally, if errors occur when running uv venv, check the Python version in Bash.

Thank you, all.

**Comment by 20481A5450** [comment]
> even though I installed the requirements.txt, it is still showing errors

Has the issue you were facing been resolved, @Sai-Jahnavi-Bachu?

**Comment by POWERFULMOVES** [comment]
(devika1) PS C:\Users\russe\Documents\GitHub\devika> python devika.py
Traceback (most recent call last):
  File "C:\Users\russe\Documents\GitHub\devika\devika.py", line 5, in <module>
    from gevent import monkey
ModuleNotFoundError: No module named 'gevent'
(devika1) PS C:\Users\russe\Documents\GitHub\devika> python --version
Python 3.11.7

**Comment by 20481A5450** [comment]
> (devika1) PS C:\Users\russe\Documents\GitHub\devika> python devika.py Traceback (most recent call last): File "C:\Users\russe\Documents\GitHub\devika\devika.py", line 5, in from gevent import monkey ModuleNotFoundError: No module named 'gevent' (devika1) PS C:\Users\russe\Documents\GitHub\devika> python --version Python 3.11.7

Have you tried the command 
```bash
pip install gevent
```

Let me know @POWERFULMOVES

**Comment by enkiGithub** [comment]
I tried pip install gevent but still got an error "No module named 'gevent'"

**Comment by Khaogamermain01** [comment]
I tried `python devika.py` and it gave me this error (In the venv environment and installed gevent already)
So then I tried `python3 devika.py` and it worked.

**Comment by manuhelpiz** [comment]
It happened to me as well and it was because I forgot to run "uv pip install -r requirements.txt" before python3 devikya.py...
