### ISSUE TITLE
openai key error

### ISSUE THREAD

**Issue by darrassi1** [stitionai/devika#453]
24.04.17 13:00:01: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'create simple calculate app\n', 'timestamp': '2024-04-17 13:00:01'}}
24.04.17 13:00:01: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 732}
Model: gemini-pro, Enum: GOOGLE
Exception in thread Thread-3 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pc\Desktop\latest\devika\devika.py", line 94, in <lambda>
    thread = Thread(target=lambda: agent.execute(message, project_name))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\Desktop\latest\devika\src\agents\agent.py", line 273, in execute
    plan = self.planner.execute(prompt, project_name_from_user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\Desktop\latest\devika\src\agents\planner\planner.py", line 70, in execute
    response = self.llm.inference(prompt, project_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\Desktop\latest\devika\src\llm\llm.py", line 88, in inference
    "OPENAI": OpenAi(),
              ^^^^^^^^
  File "C:\Users\pc\Desktop\latest\devika\src\llm\openai_client.py", line 10, in __init__
    base_url = config.get_openai_api_base_url()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\Desktop\latest\devika\src\config.py", line 50, in get_openai_api_base_url
    return self.config["API_ENDPOINTS"]["OPENAI"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'OPENAI'

**Comment by AyushRajgor** [comment]
refer this. https://github.com/stitionai/devika/blob/main/sample.config.toml
add new variables
