### ISSUE TITLE
OpenAI API is broken

### ISSUE THREAD

**Issue by temotskipa** [stitionai/devika#463]
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ttski\Downloads\devika\devika.py", line 94, in <lambda>
    thread = Thread(target=lambda: agent.execute(message, project_name))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\src\agents\agent.py", line 273, in execute
    plan = self.planner.execute(prompt, project_name_from_user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\src\agents\planner\planner.py", line 70, in execute
    response = self.llm.inference(prompt, project_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\src\llm\llm.py", line 96, in inference
    response = model.inference(self.model_id, prompt).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\src\llm\openai_client.py", line 14, in inference
    chat_completion = self.client.chat.completions.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\.venv\Lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\.venv\Lib\site-packages\openai\resources\chat\completions.py", line 581, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\.venv\Lib\site-packages\openai\_base_client.py", line 1232, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\.venv\Lib\site-packages\openai\_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\ttski\Downloads\devika\.venv\Lib\site-packages\openai\_base_client.py", line 1012, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'type': 'invalid_request_error', 'code': 'unknown_url', 'message': 'Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.', 'param': None}}

It displayed this output in the terminal. I don't know what's happening.

**Comment by ARajgor** [comment]
fixed it. fetch the latest changes
