### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by amjiddader** [stitionai/devika#479]
### Issue.
I am getting below error everytime, for normal simple files and projects its working fine.

### How To Reproduce
Steps to reproduce the behavior (example):
1. I asked devika to create a react app.
2. As simple search engine that will fetch data from xml files hosted on remote server ( like sitemap)
3. Publish that website on Vercel

### Expected behavior
It should work correctly.

### Screenshots and logs
Log posted below  

### Configuration
```
- OS: Windows
- Python version: 3.10
- Node version: 20
- bun version: 0.1.0
- search engine:  google
- Model: gemini
```

#### Additional context
[Add any other context about the problem here.](error: Exception in thread Thread-49 (): Traceback (most recent call last): File "C:\Users\Amjad\.pyenv\pyenv-win\versions\3.10.11\lib\threading.py", line 1016, in _bootstrap_inner self.run() File "C:\Users\Amjad\.pyenv\pyenv-win\versions\3.10.11\lib\threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "C:\devika\devika.py", line 90, in thread = Thread(target=lambda: agent.subsequent_execute(message, project_name)) File "C:\devika\src\agents\agent.py", line 207, in subsequent_execute self.runner.execute( File "C:\devika\src\agents\runner\runner.py", line 247, in execute self.run_code( File "C:\devika\src\agents\runner\runner.py", line 105, in run_code process = subprocess.run( File "C:\Users\Amjad\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\gevent\subprocess.py", line 2001, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\Amjad\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\gevent\subprocess.py", line 808, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\Amjad\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\gevent\subprocess.py", line 1295, in _execute_child hp, ht, pid, tid = CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified)

**Comment by matichek** [comment]
i have the same with ollama3
