### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by evrenyal** [stitionai/devika#493]
sudo docker-compose up and I got an error like this:

I changed the sample.config.toml file to config.toml and changed the contents. I did not delete either of them.

```
devika-backend-engine-1  | Traceback (most recent call last):
devika-backend-engine-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
devika-backend-engine-1  |   File "<frozen runpy>", line 88, in _run_code
devika-backend-engine-1  |   File "/home/nonroot/devika/devika.py", line 8, in <module>
devika-backend-engine-1  |     init_devika()
devika-backend-engine-1  |   File "/home/nonroot/devika/src/init.py", line 7, in init_devika
devika-backend-engine-1  |     logger = Logger()
devika-backend-engine-1  |              ^^^^^^^^
devika-backend-engine-1  |   File "/home/nonroot/devika/src/logger.py", line 11, in __init__
devika-backend-engine-1  |     config = Config()
devika-backend-engine-1  |              ^^^^^^^^
devika-backend-engine-1  |   File "/home/nonroot/devika/src/config.py", line 11, in __new__
devika-backend-engine-1  |     cls._instance._load_config()
devika-backend-engine-1  |   File "/home/nonroot/devika/src/config.py", line 23, in _load_config
devika-backend-engine-1  |     with open("sample.config.toml", "r") as f:
devika-backend-engine-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
devika-backend-engine-1  | FileNotFoundError: [Errno 2] No such file or directory: 'sample.config.toml'
devika-backend-engine-1 exited with code 1
```

**Comment by SerenityNrrd** [comment]
Go into the files and src/config.py and remove the sample. Line 17 and 23
