### ISSUE TITLE
[ISSUE] devika encounters an error and stops it 

### ISSUE THREAD

**Issue by VannyFurry** [stitionai/devika#511]
Exception in thread Thread-30 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run        
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Miles\PycharmProjects\pythonProject2\devika\devika.py", line 89, in <lambda>
    thread = Thread(target=lambda: agent.subsequent_execute(message, project_name))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\PycharmProjects\pythonProject2\devika\src\agents\agent.py", line 211, in subsequent_execute
    self.runner.execute(
  File "C:\Users\Miles\PycharmProjects\pythonProject2\devika\src\services\utils.py", line 11, in wrapper   
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\PycharmProjects\pythonProject2\devika\src\agents\runner\runner.py", line 235, in execute
    self.run_code(
  File "C:\Users\Miles\PycharmProjects\pythonProject2\devika\src\services\utils.py", line 11, in wrapper   
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\PycharmProjects\pythonProject2\devika\src\agents\runner\runner.py", line 107, in run_code
    process = subprocess.run(
              ^^^^^^^^^^^^^^^
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\subprocess.py", line 2001, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\subprocess.py", line 808, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\subprocess.py", line 1295, in _execute_child
    hp, ht, pid, tid = CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Sistem belirtilen dosyayı bulamıyor

When I try to create something with Devika, I often encounter this error and I have uninstalled and reinstalled gevent still the same i need help!

**Comment by zarigata** [comment]
same error for me as well
