### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by Joshua-Grant-kana** [stitionai/devika#515]
I'm currrently having this problem with running Devika

### Describe your issue
Traceback (most recent call last):
  File "C:\Users\AstriNET ENT\Downloads\devika-main\devika-main\devika.py", line 8, in <module>
    init_devika()
  File "C:\Users\AstriNET ENT\Downloads\devika-main\devika-main\src\init.py", line 27, in init_devika
    from src.bert.sentence import SentenceBert
  File "C:\Users\AstriNET ENT\Downloads\devika-main\devika-main\src\bert\sentence.py", line 1, in <module>
    from keybert import KeyBERT
  File "C:\Users\AstriNET ENT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keybert\__init__.py", line 1, in <module>
    from keybert._llm import KeyLLM
  File "C:\Users\AstriNET ENT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keybert\_llm.py", line 4, in <module>
    from sentence_transformers import util
  File "C:\Users\AstriNET ENT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "C:\Users\AstriNET ENT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "C:\Users\AstriNET ENT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sentence_transformers\datasets\DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "C:\Users\AstriNET ENT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\AstriNET ENT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\lib\shm.dll" or one of its dependencies.

### Expected behavior
After installing and then I ran Devika as usual python devika.py I got this error and I need help.

### Screenshots and logs
![Screenshot 2024-04-30 082113](https://github.com/stitionai/devika/assets/61407084/e2f43304-6a1d-4180-a149-f39e2b495c4f)

### Configuration
```
- OS: [e.g. Windows, Linux, MacOS]
I have all the packages and dependencies installed
```

**Comment by Massea0** [comment]
I have the same issue ＞﹏＜
+1
