### ISSUE TITLE
[Bug]The button“select search engine”and"select models"is not working without ollama config

### ISSUE THREAD

**Issue by linuffe** [stitionai/devika#553]
### Describe the bug 
Runtime:
Python 3.11
Windows 11x64
*I want to run the app using SAAS API only so I didn't intall ollama and relevent localized LLMs
After installation, when I open the frontend, I find I can't press the “select search engine”and"select models" button!
And the backend just give some errors relating to ollama, 
I am wondering how to manage it？

### How To Reproduce
Steps to reproduce the be
<img width="917" alt="backend" src="https://github.com/stitionai/devika/assets/52554472/254a53a0-886d-4d15-9406-8af426d2e9fc">
<img width="1895" alt="devika_webui" src="https://github.com/stitionai/devika/assets/52554472/04e12aba-6a89-45a1-8712-efa0aec2f971">

<img width="961" alt="frontend" src="https://github.com/stitionai/devika/assets/52554472/b5ff1f08-3f9e-4218-bf4c-7850bc823c67">
Below is my settings:
<img width="1517" alt="settings" src="https://github.com/stitionai/devika/assets/52554472/45b96df0-3651-497d-89e5-eba0b0583030">
<img width="1100" alt="setting2" src="https://github.com/stitionai/devika/assets/52554472/af0364d6-826b-4fa5-ac78-f79020b69800">

**Comment by Polygons1** [comment]
any frontend console errors?

**Comment by linuffe** [comment]
But everytime I swith to the home page, here is a Error:

[2024-05-12 21:19:25,883] ERROR in app: Exception on /api/data [GET]
Traceback (most recent call last):
  File "F:\devika-main\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\devika-main\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\devika-main\.venv\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "F:\devika-main\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\devika-main\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\devika-main\src\logger.py", line 59, in wrapper
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\devika-main\devika.py", line 59, in data
    models = LLM().list_models()
             ^^^^^
  File "F:\devika-main\src\llm\llm.py", line 62, in __init__
    self.models["OLLAMA"] = [(model["name"].split(":")[0], model["name"]) for model in ollama.models]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by Indratejreddy** [comment]
Same for me I tried to check it out but something is wrong I can see internal server error 
![image](https://github.com/stitionai/devika/assets/66834653/a9f92c05-f163-4c7f-8dd3-e77ebe4cddde)

**Comment by ARajgor** [comment]
you already have the ollama installed in your system.
As per your LOG it says ollama available. can you type `ollama` in your system terminal to check it.

**Comment by linuffe** [comment]
![image](https://github.com/stitionai/devika/assets/52554472/eb5d0bb5-ace5-4c2b-89e5-628135e36610)

**Comment by Unrealisedd** [comment]
so how do I fix this..? I have valid API keys set up and ollama running yet I cant choose a search engine nor model

**Comment by oviedo97fer** [comment]
any update for this? 
I stuck in same error using Devika on local with local ollama models.
First running:
1. ollama serve
2. python devika.py

Result: 
```
25.01.07 23:33:27: root: INFO   : Ollama available
25.01.07 23:33:28: root: INFO   : Devika is up and running!
```
but buttons for Search Engine and Select models doesnt work. Also see this error:
```
[2025-01-07 23:33:32,781] ERROR in app: Exception on /api/data [GET]
```
---
If running reverse (first devika then ollama serve) buttons work fine, but ollama not show models
![image](https://github.com/user-attachments/assets/d3a4d858-3713-4393-a117-91e913101b1b)

Warning:
```
25.01.07 23:39:17: root: WARNING: Ollama not available
25.01.07 23:39:17: root: WARNING: run ollama server to use ollama models otherwise use API models
```

**Comment by pammikoundi** [comment]
Ollama changed the key that was previously name, but is now model, then updating your code to consistently use model should resolve the issue. Files needing changes:

<img width="840" alt="Image" src="https://github.com/user-attachments/assets/abce4e3a-cfae-4d62-a949-5ab220e26db1" />

**Comment by Unrealisedd** [comment]
Hey, if anyone still struggles on this I wanted to get back to it. My issue was that the key was conflicting with the local installation. I wanted to run it using the local installation but it was conflicting with the key I configured. You either remove the ollama installation OR remove all api keys.
