### ISSUE TITLE
devika 

### ISSUE THREAD

**Issue by werruww** [stitionai/devika#604]
not work

**Comment by werruww** [comment]
Lists do not open and project name does not appear

**Comment by darrassi1** [comment]
try this PR #603

**Comment by werruww** [comment]
Is it possible to upload the entire repaired files?

**Comment by werruww** [comment]
https://github.com/stitionai/devika/pull/603

**Comment by werruww** [comment]
(base) C:\WINDOWS\system32>cd C:\Users\m\Desktop\p

(base) C:\Users\m\Desktop\p>git clone https://github.com/stitionai/devika.git
Cloning into 'devika'...
remote: Enumerating objects: 1483, done.
remote: Counting objects: 100% (637/637), done.
remote: Compressing objects: 100% (202/202), done.
Receiving objects: 100% (1483/1483), 6.07 MiB | 3.32 MiB/s, done.
Resolving deltas:   1% (9/864), reused 449 (delta 434), pack-reused 846Resolving deltas:   0% (0/864)
Resolving deltas: 100% (864/864), done.

(base) C:\Users\m\Desktop\p>cd devika

(base) C:\Users\m\Desktop\p\devika>gh pr checkout 603
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 71 (delta 42), reused 15 (delta 6), pack-reused 0
Unpacking objects: 100% (71/71), 23.13 KiB | 8.00 KiB/s, done.
From https://github.com/stitionai/devika
 * [new ref]         refs/pull/603/head -> darrassi1/main
Switched to branch 'darrassi1/main'

(base) C:\Users\m\Desktop\p\devika>uv venv
Using Python 3.11.5 interpreter at: C:\Users\m\anaconda3\python.exe
Creating virtualenv at: .venv
Activate with: .venv\Scripts\activate

(base) C:\Users\m\Desktop\p\devika>.venv\Scripts\activate

(devika) (base) C:\Users\m\Desktop\p\devika>uv pip install -r requirements.txt
Resolved 143 packages in 7.43s
Downloaded 2 packages in 5.57s
Installed 143 packages in 1m 05s
 + annotated-types==0.7.0
 + anthropic==0.28.1
 + anyio==4.4.0
 + arabic-reshaper==3.0.0
 + asn1crypto==1.5.1
 + beautifulsoup4==4.12.3
 + bidict==0.23.1
 + blinker==1.8.2
 + cachetools==5.3.3
 + certifi==2024.6.2
 + cffi==1.16.0
 + chardet==5.2.0
 + charset-normalizer==3.3.2
 + click==8.1.7
 + colorama==0.4.6
 + cryptography==42.0.8
 + cssselect2==0.7.0
 + distro==1.9.0
 + dnspython==2.6.1
 + duckduckgo-search==6.1.6
 + eventlet==0.36.1
 + fastlogging==1.0.0
 + filelock==3.15.1
 + flask==3.0.3
 + flask-cors==4.0.1
 + flask-socketio==5.3.6
 + fsspec==2024.6.0
 + gevent==24.2.1
 + gevent-websocket==0.10.1
 + gitdb==4.0.11
 + gitpython==3.1.43
 + google-ai-generativelanguage==0.6.4
 + google-api-core==2.19.0
 + google-api-python-client==2.133.0
 + google-auth==2.30.0
 + google-auth-httplib2==0.2.0
 + google-generativeai==0.6.0
 + googleapis-common-protos==1.63.1
 + greenlet==3.0.3
 + groq==0.9.0
 + grpcio==1.64.1
 + grpcio-status==1.62.2
 + h11==0.14.0
 + html5lib==1.1
 + httpcore==1.0.5
 + httplib2==0.22.0
 + httpx==0.27.0
 + huggingface-hub==0.23.4
 + idna==3.7
 + iniconfig==2.0.0
 + intel-openmp==2021.4.0
 + itsdangerous==2.2.0
 + jinja2==3.1.4
 + jiter==0.4.2
 + joblib==1.4.2
 + keybert==0.8.5
 + lxml==5.2.2
 + markdown==3.6
 + markdown-it-py==3.0.0
 + markdownify==0.12.1
 + markupsafe==2.1.5
 + mdurl==0.1.2
 + mistletoe==1.3.0
 + mistralai==0.3.0
 + mkl==2021.4.0
 + mpmath==1.3.0
 + netlify-py==0.1.0
 + networkx==3.3
 + numpy==2.0.0
 + ollama==0.2.1
 + openai==1.34.0
 + orjson==3.10.5
 + oscrypto==1.3.0
 + packaging==24.1
 + pdfminer-six==20231228
 + pillow==10.3.0
 + playwright==1.44.0
 + pluggy==1.5.0
 + proto-plus==1.23.0
 + protobuf==4.25.3
 + pyasn1==0.6.0
 + pyasn1-modules==0.4.0
 + pycparser==2.22
 + pydantic==2.7.4
 + pydantic-core==2.18.4
 + pyee==11.1.0
 + pygments==2.18.0
 + pyhanko==0.25.0
 + pyhanko-certvalidator==0.26.3
 + pyparsing==3.1.2
 + pypdf==4.2.0
 + pypng==0.20220715.0
 + pyreqwest-impersonate==0.4.7
 + pytest==8.2.2
 + pytest-base-url==2.1.0
 + pytest-playwright==0.5.0
 + python-bidi==0.4.2
 + python-engineio==4.9.1
 + python-slugify==8.0.4
 + python-socketio==5.11.2
 + pyyaml==6.0.1
 + qrcode==7.4.2
 + regex==2024.5.15
 + reportlab==4.2.0
 + requests==2.32.3
 + rich==13.7.1
 + rsa==4.9
 + safetensors==0.4.3
 + scikit-learn==1.5.0
 + scipy==1.13.1
 + sentence-transformers==3.0.1
 + setuptools==70.0.0
 + simple-websocket==1.0.0
 + six==1.16.0
 + smmap==5.0.1
 + sniffio==1.3.1
 + soupsieve==2.5
 + sqlalchemy==2.0.30
 + sqlmodel==0.0.19
 + svglib==1.5.1
 + sympy==1.12.1
 + tbb==2021.12.0
 + text-unidecode==1.3
 + threadpoolctl==3.5.0
 + tiktoken==0.7.0
 + tinycss2==1.3.0
 + tokenizers==0.19.1
 + toml==0.10.2
 + torch==2.3.1
 + tqdm==4.66.4
 + transformers==4.41.2
 + typing-extensions==4.12.2
 + tzdata==2024.1
 + tzlocal==5.2
 + uritemplate==4.1.1
 + uritools==4.0.3
 + urllib3==2.2.2
 + webencodings==0.5.1
 + werkzeug==3.0.3
 + wsproto==1.2.0
 + xhtml2pdf==0.2.16
 + zope-event==5.0
 + zope-interface==6.4.post2

(devika) (base) C:\Users\m\Desktop\p\devika>playwright install --with-deps

(devika) (base) C:\Users\m\Desktop\p\devika>python devika.py
24.06.17 10:28:44: root: INFO   : Initializing Devika...
24.06.17 10:28:44: root: INFO   : checking configurations...
24.06.17 10:28:44: root: INFO   : Initializing Prerequisites Jobs...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\m\Desktop\p\devika\devika.py", line 8, in <module>
    init_devika()
  File "C:\Users\m\Desktop\p\devika\src\init.py", line 27, in init_devika
    from src.bert.sentence import SentenceBert
  File "C:\Users\m\Desktop\p\devika\src\bert\sentence.py", line 1, in <module>
    from keybert import KeyBERT
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\__init__.py", line 3, in <module>
    from keybert._llm import KeyLLM
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\_llm.py", line 4, in <module>
    from sentence_transformers import util
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\__init__.py", line 15, in <module>
    from sentence_transformers.trainer import SentenceTransformerTrainer
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\trainer.py", line 10, in <module>
    from transformers import EvalPrediction, PreTrainedTokenizerBase, Trainer, TrainerCallback
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\utils\import_utils.py", line 1525, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\utils\import_utils.py", line 1535, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\m\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer.py", line 71, in <module>
    from .optimization import Adafactor, get_scheduler
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\optimization.py", line 27, in <module>
    from .trainer_pt_utils import LayerWiseDummyOptimizer, LayerWiseDummyScheduler
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer_pt_utils.py", line 235, in <module>
    device: Optional[torch.device] = torch.device("cuda"),
C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer_pt_utils.py:235: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: Optional[torch.device] = torch.device("cuda"),
24.06.17 10:30:31: root: INFO   : Loading sentence-transformer BERT models...
Traceback (most recent call last):
  File "C:\Users\m\Desktop\p\devika\devika.py", line 8, in <module>
    init_devika()
  File "C:\Users\m\Desktop\p\devika\src\init.py", line 31, in init_devika
    SentenceBert(prompt).extract_keywords()
  File "C:\Users\m\Desktop\p\devika\src\bert\sentence.py", line 9, in extract_keywords
    keywords = self.kw_model.extract_keywords(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\_model.py", line 195, in extract_keywords
    doc_embeddings = self.model.embed(docs)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\backend\_sentencetransformers.py", line 67, in embed    embeddings = self.embedding_model.encode(documents, **self.encode_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 568, in encode
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 568, in <listcomp>
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                 ^^^^^^^^^^^
RuntimeError: Numpy is not available

(devika) (base) C:\Users\m\Desktop\p\devika>

**Comment by werruww** [comment]
(base) C:\Users\m>cd C:\Users\m\Desktop\p

(base) C:\Users\m\Desktop\p>git clone https://github.com/stitionai/devika.git
Cloning into 'devika'...
remote: Enumerating objects: 1483, done.
remote: Counting objects: 100% (648/648), done.
remote: Compressing objects: 100% (205/205), done.
Receiving objects: 100% (1483/1483), 6.07 MiB | 1.54 MiB/s, done.
remote: Total 1483 (delta 519), reused 457 (delta 442), pack-reused 835
Resolving deltas: 100% (866/866), done.

(base) C:\Users\m\Desktop\p>cd devika

(base) C:\Users\m\Desktop\p\devika>uv venv
Using Python 3.11.5 interpreter at: C:\Users\m\anaconda3\python.exe
Creating virtualenv at: .venv
Activate with: .venv\Scripts\activate

(base) C:\Users\m\Desktop\p\devika>.venv\Scripts\activate

(devika) (base) C:\Users\m\Desktop\p\devika>uv pip install -r requirements.txt
Resolved 143 packages in 1.12s
Installed 143 packages in 30.15s
 + annotated-types==0.7.0
 + anthropic==0.28.1
 + anyio==4.4.0
 + arabic-reshaper==3.0.0
 + asn1crypto==1.5.1
 + beautifulsoup4==4.12.3
 + bidict==0.23.1
 + blinker==1.8.2
 + cachetools==5.3.3
 + certifi==2024.6.2
 + cffi==1.16.0
 + chardet==5.2.0
 + charset-normalizer==3.3.2
 + click==8.1.7
 + colorama==0.4.6
 + cryptography==42.0.8
 + cssselect2==0.7.0
 + distro==1.9.0
 + dnspython==2.6.1
 + duckduckgo-search==6.1.6
 + eventlet==0.36.1
 + fastlogging==1.0.0
 + filelock==3.15.1
 + flask==3.0.3
 + flask-cors==4.0.1
 + flask-socketio==5.3.6
 + fsspec==2024.6.0
 + gevent==24.2.1
 + gevent-websocket==0.10.1
 + gitdb==4.0.11
 + gitpython==3.1.43
 + google-ai-generativelanguage==0.6.4
 + google-api-core==2.19.0
 + google-api-python-client==2.133.0
 + google-auth==2.30.0
 + google-auth-httplib2==0.2.0
 + google-generativeai==0.6.0
 + googleapis-common-protos==1.63.1
 + greenlet==3.0.3
 + groq==0.9.0
 + grpcio==1.64.1
 + grpcio-status==1.62.2
 + h11==0.14.0
 + html5lib==1.1
 + httpcore==1.0.5
 + httplib2==0.22.0
 + httpx==0.27.0
 + huggingface-hub==0.23.4
 + idna==3.7
 + iniconfig==2.0.0
 + intel-openmp==2021.4.0
 + itsdangerous==2.2.0
 + jinja2==3.1.4
 + jiter==0.4.2
 + joblib==1.4.2
 + keybert==0.8.5
 + lxml==5.2.2
 + markdown==3.6
 + markdown-it-py==3.0.0
 + markdownify==0.12.1
 + markupsafe==2.1.5
 + mdurl==0.1.2
 + mistletoe==1.3.0
 + mistralai==0.3.0
 + mkl==2021.4.0
 + mpmath==1.3.0
 + netlify-py==0.1.0
 + networkx==3.3
 + numpy==2.0.0
 + ollama==0.2.1
 + openai==1.34.0
 + orjson==3.10.5
 + oscrypto==1.3.0
 + packaging==24.1
 + pdfminer-six==20231228
 + pillow==10.3.0
 + playwright==1.44.0
 + pluggy==1.5.0
 + proto-plus==1.23.0
 + protobuf==4.25.3
 + pyasn1==0.6.0
 + pyasn1-modules==0.4.0
 + pycparser==2.22
 + pydantic==2.7.4
 + pydantic-core==2.18.4
 + pyee==11.1.0
 + pygments==2.18.0
 + pyhanko==0.25.0
 + pyhanko-certvalidator==0.26.3
 + pyparsing==3.1.2
 + pypdf==4.2.0
 + pypng==0.20220715.0
 + pyreqwest-impersonate==0.4.7
 + pytest==8.2.2
 + pytest-base-url==2.1.0
 + pytest-playwright==0.5.0
 + python-bidi==0.4.2
 + python-engineio==4.9.1
 + python-slugify==8.0.4
 + python-socketio==5.11.2
 + pyyaml==6.0.1
 + qrcode==7.4.2
 + regex==2024.5.15
 + reportlab==4.2.0
 + requests==2.32.3
 + rich==13.7.1
 + rsa==4.9
 + safetensors==0.4.3
 + scikit-learn==1.5.0
 + scipy==1.13.1
 + sentence-transformers==3.0.1
 + setuptools==70.0.0
 + simple-websocket==1.0.0
 + six==1.16.0
 + smmap==5.0.1
 + sniffio==1.3.1
 + soupsieve==2.5
 + sqlalchemy==2.0.30
 + sqlmodel==0.0.19
 + svglib==1.5.1
 + sympy==1.12.1
 + tbb==2021.12.0
 + text-unidecode==1.3
 + threadpoolctl==3.5.0
 + tiktoken==0.7.0
 + tinycss2==1.3.0
 + tokenizers==0.19.1
 + toml==0.10.2
 + torch==2.3.1
 + tqdm==4.66.4
 + transformers==4.41.2
 + typing-extensions==4.12.2
 + tzdata==2024.1
 + tzlocal==5.2
 + uritemplate==4.1.1
 + uritools==4.0.3
 + urllib3==2.2.2
 + webencodings==0.5.1
 + werkzeug==3.0.3
 + wsproto==1.2.0
 + xhtml2pdf==0.2.16
 + zope-event==5.0
 + zope-interface==6.4.post2

(devika) (base) C:\Users\m\Desktop\p\devika>playwright install --with-deps

(devika) (base) C:\Users\m\Desktop\p\devika>python devika.py
24.06.17 10:37:54: root: INFO   : Initializing Devika...
24.06.17 10:37:54: root: INFO   : checking configurations...
24.06.17 10:37:54: root: INFO   : Initializing Prerequisites Jobs...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\m\Desktop\p\devika\devika.py", line 8, in <module>
    init_devika()
  File "C:\Users\m\Desktop\p\devika\src\init.py", line 27, in init_devika
    from src.bert.sentence import SentenceBert
  File "C:\Users\m\Desktop\p\devika\src\bert\sentence.py", line 1, in <module>
    from keybert import KeyBERT
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\__init__.py", line 3, in <module>
    from keybert._llm import KeyLLM
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\_llm.py", line 4, in <module>
    from sentence_transformers import util
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\__init__.py", line 15, in <module>
    from sentence_transformers.trainer import SentenceTransformerTrainer
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\trainer.py", line 10, in <module>
    from transformers import EvalPrediction, PreTrainedTokenizerBase, Trainer, TrainerCallback  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\utils\import_utils.py", line 1525, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\utils\import_utils.py", line 1535, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\m\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer.py", line 71, in <module>
    from .optimization import Adafactor, get_scheduler
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\optimization.py", line 27, in <module>
    from .trainer_pt_utils import LayerWiseDummyOptimizer, LayerWiseDummyScheduler
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer_pt_utils.py", line 235, in <module>
    device: Optional[torch.device] = torch.device("cuda"),
C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer_pt_utils.py:235: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: Optional[torch.device] = torch.device("cuda"),
24.06.17 10:38:27: root: INFO   : Loading sentence-transformer BERT models...
Traceback (most recent call last):
  File "C:\Users\m\Desktop\p\devika\devika.py", line 8, in <module>
    init_devika()
  File "C:\Users\m\Desktop\p\devika\src\init.py", line 31, in init_devika
    SentenceBert(prompt).extract_keywords()
  File "C:\Users\m\Desktop\p\devika\src\bert\sentence.py", line 9, in extract_keywords
    keywords = self.kw_model.extract_keywords(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\_model.py", line 195, in extract_keywords
    doc_embeddings = self.model.embed(docs)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\backend\_sentencetransformers.py", line 67, in embed
    embeddings = self.embedding_model.encode(documents, **self.encode_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 568, in encode
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 568, in <listcomp>
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                 ^^^^^^^^^^^
RuntimeError: Numpy is not available

(devika) (base) C:\Users\m\Desktop\p\devika>python devika.py
24.06.17 10:41:53: root: INFO   : Initializing Devika...
24.06.17 10:41:53: root: INFO   : checking configurations...
24.06.17 10:41:53: root: INFO   : Initializing Prerequisites Jobs...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\m\Desktop\p\devika\devika.py", line 8, in <module>
    init_devika()
  File "C:\Users\m\Desktop\p\devika\src\init.py", line 27, in init_devika
    from src.bert.sentence import SentenceBert
  File "C:\Users\m\Desktop\p\devika\src\bert\sentence.py", line 1, in <module>
    from keybert import KeyBERT
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\__init__.py", line 3, in <module>
    from keybert._llm import KeyLLM
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\_llm.py", line 4, in <module>
    from sentence_transformers import util
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\__init__.py", line 15, in <module>
    from sentence_transformers.trainer import SentenceTransformerTrainer
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\trainer.py", line 10, in <module>
    from transformers import EvalPrediction, PreTrainedTokenizerBase, Trainer, TrainerCallback
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\utils\import_utils.py", line 1525, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\utils\import_utils.py", line 1535, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\m\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer.py", line 71, in <module>
    from .optimization import Adafactor, get_scheduler
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\optimization.py", line 27, in <module>
    from .trainer_pt_utils import LayerWiseDummyOptimizer, LayerWiseDummyScheduler
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer_pt_utils.py", line 235, in <module>
    device: Optional[torch.device] = torch.device("cuda"),
C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\transformers\trainer_pt_utils.py:235: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: Optional[torch.device] = torch.device("cuda"),
24.06.17 10:42:00: root: INFO   : Loading sentence-transformer BERT models...
modules.json: 100%|████████████████████████████████████████████████████████████████████████████████| 349/349 [00:00<?, ?B/s]
C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\m\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
config_sentence_transformers.json: 100%|███████████████████████████████████████████████████████████| 116/116 [00:00<?, ?B/s]
README.md: 100%|███████████████████████████████████████████████████████████████████████████████| 10.7k/10.7k [00:00<?, ?B/s]
sentence_bert_config.json: 100%|█████████████████████████████████████████████████████████████████| 53.0/53.0 [00:00<?, ?B/s]
config.json: 100%|█████████████████████████████████████████████████████████████████████████| 612/612 [00:00<00:00, 39.2kB/s]
model.safetensors: 100%|███████████████████████████████████████████████████████████████| 90.9M/90.9M [00:25<00:00, 3.53MB/s]
tokenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████| 350/350 [00:00<?, ?B/s]
vocab.txt: 100%|██████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 872kB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 1.11MB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 7.18kB/s]
1_Pooling/config.json: 100%|███████████████████████████████████████████████████████████████████████| 190/190 [00:00<?, ?B/s]
Traceback (most recent call last):
  File "C:\Users\m\Desktop\p\devika\devika.py", line 8, in <module>
    init_devika()
  File "C:\Users\m\Desktop\p\devika\src\init.py", line 31, in init_devika
    SentenceBert(prompt).extract_keywords()
  File "C:\Users\m\Desktop\p\devika\src\bert\sentence.py", line 9, in extract_keywords
    keywords = self.kw_model.extract_keywords(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\_model.py", line 195, in extract_keywords
    doc_embeddings = self.model.embed(docs)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\keybert\backend\_sentencetransformers.py", line 67, in embed
    embeddings = self.embedding_model.encode(documents, **self.encode_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 568, in encode
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m\Desktop\p\devika\.venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 568, in <listcomp>
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                 ^^^^^^^^^^^
RuntimeError: Numpy is not available
