### ISSUE TITLE
[Bug] EPERM: Operation not permitted

### ISSUE THREAD

**Issue by CosmicHazel** [stitionai/devika#609]
### Describe the bug 
Cannot run bun run start

### How To Reproduce
Ubuntu, WSL.

Follow the instructions in readme exactly

### Expected behavior
server starts

### Screenshots and logs
```
(devika) (base) me@HazelDesktop:~/devika/ui$ bun run start
$ vite build && vite preview
vite v5.2.13 building SSR bundle for production...
13622 |     else {
13623 |         process.stdout.write(output.substring(0, process.stdout.columns - 1));
13624 |     }
13625 | }
13626 | function clearLine$1() {
13627 |     process.stdout.clearLine(0);
        ^
EPERM: Operation not permitted
   errno: -1
 syscall: "write"
      fd: 15

      at write (native:1:1)
      at node:stream:171:43
      at clearLine$1 (/home/me/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:13627:20)
      at writeLine (/home/me/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31570:87)
      at /home/me/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31302:10
      at /home/me/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31592:13
      at transform (/home/me/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31328:26)
      at /home/me/devika/ui/node_modules/rollup/dist/es/shared/node-entry.js:19774:40

Bun v1.1.15 (Linux x64)
error: script "start" exited with code 1
```

### Configuration
```
- OS: Linux
- Python version Python 3.10.12
- Node version: v20.15.0
- bun version:1.1.15
- search engine: n/a
- Model: n/a
```

**Comment by atharvaj1234** [comment]
## Here are few steps you an try:

### 1. Check File Permissions
Ensure that the user running the bun run start command has the necessary permissions to access and modify the files and directories involved in the build process. This includes the project directory itself and any output directories like .vite.

`ls -l <project-directory>`

Look for lines that show the permissions for directories and files. If necessary, adjust the permissions using `chmod` or change the ownership with `chown`.


### 2. Update Dependencies
Ensure all your dependencies, including Vite and Bun, are up to date. Sometimes, bugs that cause permission issues are fixed in newer versions.

Update your packages:

``` 
npm update
# or
yarn upgrade
```


### 3. Completely remove bun and reinstall it
If you have downloaded/installed bun from snap or any where else remove it and install it using following command:
```
curl -fsSL https://bun.sh/install | bash # for macOS, Linux, and WSL
```

**Comment by swisstackle** [comment]
I have the same issue,. What was the solution?
