### ISSUE TITLE
EPERM: Operation not permitted errno: 1

### ISSUE THREAD

**Issue by sbera7** [stitionai/devika#616]
I am facing an issue when I ran the command ```bun run start```

here is the complete picture
```
(devika) m0nku@pop-os:~/Documents/Temporary/devika/ui$ bun run start
$ vite build && vite preview
vite v5.2.13 building SSR bundle for production...
13622 |     else {
13623 |         process.stdout.write(output.substring(0, process.stdout.columns - 1));
13624 |     }
13625 | }
13626 | function clearLine$1() {
13627 |     process.stdout.clearLine(0);
        ^
EPERM: Operation not permitted
   errno: -1
 syscall: "write"
      fd: 15

      at write (native:1:1)
      at node:stream:171:43
      at clearLine$1 (/home/m0nku/Documents/Temporary/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:13627:20)
      at writeLine (/home/m0nku/Documents/Temporary/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31570:87)
      at /home/m0nku/Documents/Temporary/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31302:10
      at /home/m0nku/Documents/Temporary/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31592:13
      at transform (/home/m0nku/Documents/Temporary/devika/ui/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:31328:26)
      at /home/m0nku/Documents/Temporary/devika/ui/node_modules/rollup/dist/es/shared/node-entry.js:19774:40

Bun v1.1.16 (Linux x64)
error: script "start" exited with code 1
```

**Comment by alpernae** [comment]
hey buddy I'm not a project coder I just saw your issues and found this check out this https://github.com/stitionai/devika/issues/609

**Comment by sbera7** [comment]
It did not help :)
