### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DefamationStation** [stitionai/devika#638]
### Describe the bug 
devika modulenotfounderror

### How To Reproduce
Steps to reproduce the behavior (example):
1. Install devika
2. try to run devika

Windows 11, python 3.11.9

mistralai package exists 100% confirmed

devika>python devika.py
24.08.11 19:38:33: root: INFO   : Initializing Devika...
24.08.11 19:38:33: root: INFO   : checking configurations...
24.08.11 19:38:33: root: INFO   : Initializing Prerequisites Jobs...
24.08.11 19:38:35: root: INFO   : Loading sentence-transformer BERT models...
24.08.11 19:38:37: root: INFO   : BERT model loaded successfully.
Traceback (most recent call last):
  File "C:\Users\frenz\Downloads\LLMs\devika\devika.py", line 24, in <module>
    from src.agents import Agent
  File "C:\Users\frenz\Downloads\LLMs\devika\src\agents\__init__.py", line 1, in <module>
    from .agent import Agent
  File "C:\Users\frenz\Downloads\LLMs\devika\src\agents\agent.py", line 1, in <module>
    from .planner import Planner
  File "C:\Users\frenz\Downloads\LLMs\devika\src\agents\planner\__init__.py", line 1, in <module>
    from .planner import Planner
  File "C:\Users\frenz\Downloads\LLMs\devika\src\agents\planner\planner.py", line 3, in <module>
    from src.llm import LLM
  File "C:\Users\frenz\Downloads\LLMs\devika\src\llm\__init__.py", line 1, in <module>
    from .llm import LLM
  File "C:\Users\frenz\Downloads\LLMs\devika\src\llm\llm.py", line 11, in <module>
    from .mistral_client import MistralAi
  File "C:\Users\frenz\Downloads\LLMs\devika\src\llm\mistral_client.py", line 2, in <module>
    from mistralai.models.chat_completion import ChatMessage
ModuleNotFoundError: No module named 'mistralai.models.chat_completion'

**Comment by yblis** [comment]
Hello,

I encountered the same issue, it seems to be due to a new version of `mistralai`, so I opted for an older version prior to version 1.0.0. In the `requirements.txt`, I replaced `mistralai` with `mistralai==0.4.2`.

**Comment by barokoVlad** [comment]
> I replaced `mistralai` with `mistralai==0.4.2`.

Thanks Bro!
This works for me.
