### ISSUE TITLE
FastLogging can't be installed on Windows

### ISSUE THREAD

**Issue by vegax87** [stitionai/devika#64]
I followed every step in the installation:
```
ollama serve
git clone https://github.com/stitionai/devika.git
cd devika/
uv venv
uv pip install -r requirements.txt
cd ui/
bun install
bun run dev
python3 devika.py
``` 
when I type python devika.py on windows it says "Traceback (most recent call last):
  File "D:\devika\devika.py", line 9, in <module>
    from src.init import init_devika
  File "D:\devika\src\init.py", line 4, in <module>
    from src.logger import Logger
  File "D:\devika\src\logger.py", line 1, in <module>
    from fastlogging import LogInit
ModuleNotFoundError: No module named 'fastlogging' 

fastlogging is the only library that I can't install on Windows 10, would it be possible to replace it with [picologging](https://github.com/microsoft/picologging)?

**Comment by RohitX0X** [comment]
Happened with me too, it got fixed after i switched to using uv/venv for the project

**Comment by mohammedpithapur** [comment]
when i run "source .venv/bin/activate  " it says ' 'source' is not recognized as an internal or external command,
operable program or batch file.'

**Comment by ARajgor** [comment]
create venv and install the requirements.txt

**Comment by k-gordon** [comment]
> when i run "source .venv/bin/activate " it says ' 'source' is not recognized as an internal or external command, operable program or batch file.'

If you're on Windows run `.venv/Scripts/activate` sans `source`
