### ISSUE TITLE
Can't make changes after outputting the first iteration.

### ISSUE THREAD

**Issue by sonicino2** [stitionai/devika#66]
Here's the code. In windows, I believe this is dealing with the devika.py.

Exception in thread Thread-10106 (<lambda>):
Traceback (most recent call last):
  File "c:\python312\Lib\threading.py", line 1073, in _bootstrap_inner 
    self.run()
  File "c:\python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sonic\Downloads\Devika\devika.py", line 103, in <lambda>
    thread = Thread(

  File "C:\Users\sonic\Downloads\Devika\src\agents\agent.py", line 220, in subsequent_execute
    system_os=os_system,
              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'os_system' where it is not associated with a value

**Comment by flamasz** [comment]
Getting similar issue

Exception in thread Thread-29412 (<lambda>):
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/macbook/Documents/devika/devika.py", line 103, in <lambda>
    target=lambda: Agent(base_model=base_model).subsequent_execute(message, project_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/devika/src/agents/agent.py", line 233, in subsequent_execute
    system_os=os_system,
              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'os_system' where it is not associated with a value

**Comment by RohitX0X** [comment]
Could be because execute agent api is not getting called after first iteration, A workaround was creating new project everytime

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
