### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'mistralai.models.chat_completion'

### ISSUE THREAD

**Issue by WahahaZeng** [stitionai/devika#677]
### Describe the bug 
Traceback (most recent call last):
  File "/home/xyz/HarmBench/generate_completions.py", line 9, in <module>
    from api_models import api_models_map
  File "/home/xyz/HarmBench/api_models.py", line 11, in <module>
    from mistralai.models.chat_completion import ChatMessage
ModuleNotFoundError: No module named 'mistralai.models.chat_completion'

The version is am using is the latest one 
$ pip list |grep mistralai
mistralai                                1.2.5

I also tried some old version like "mistralai==1.2.0", "mistralai==1.0.1", but the bug is still there

```
- OS: Linux
- Python version: 3.10.15
```

This bug was reported before in [#640](https://github.com/stitionai/devika/issues/640)

**Comment by micedevai** [comment]
The error you're encountering, `ModuleNotFoundError: No module named 'mistralai.models.chat_completion'`, suggests that the module `mistralai.models.chat_completion` does not exist in the version of the `mistralai` library that you have installed (version `1.2.5` or any older version). Here are several steps you can take to address this:

### Steps to Fix:

#### 1. **Check the Available Modules in the Installed Version of Mistralai**
   It's possible that the structure of the `mistralai` library has changed in recent versions. To check the available modules, navigate to the installation directory of `mistralai` and inspect its contents.

   - To find the installation location of `mistralai`, run the following:
     ```bash
     pip show mistralai
     ```
     This will provide the path to the `mistralai` package.

   - Once you have the path, navigate to it:
     ```bash
     cd <path_to_mistralai>/mistralai/models
     ```

     Look for the `chat_completion.py` file. If it doesn't exist, it confirms that the module has either been removed or renamed.

#### 2. **Consult Mistralai Documentation/Changelog**
   - **Check the Documentation:** Mistralai may have changed its module structure in recent versions, which could explain why the `chat_completion` module is missing.
     - Visit the official documentation: [[Mistralai Docs](https://mistralai.ai/docs/)](https://mistralai.ai/docs/)
     - Look for updates regarding the changes in version 1.2.0+ that could affect the `models` submodule.

   - **Check the GitHub Repo for Changelog:** Review the [[Mistralai GitHub repo](https://github.com/mistralai/mistralai)](https://github.com/mistralai/mistralai) to see if there have been any breaking changes or deprecations related to the `chat_completion` module in the changelog.

#### 3. **Use the Correct Version**
   Since you've already tried several versions, it's important to figure out if the `chat_completion` module was present in earlier versions. It's possible that the module was either removed or relocated in a recent release. 

   - **Try Downgrading to a Specific Version**: 
     If the module was present in a previous version, try to find which version it existed in by checking the release notes. You can also search for older versions of the package and install them with:
     ```bash
     pip install mistralai==<specific_version>
     ```

   For example:
   ```bash
   pip install mistralai==1.1.0
   ```

   - **Check Version History**: You can also check the GitHub releases for Mistralai to understand which versions contained `chat_completion`. Visit the [[Mistralai releases page](https://github.com/mistralai/mistralai/releases)](https://github.com/mistralai/mistralai/releases).

#### 4. **Explore an Alternative Approach**
   If you cannot find the `chat_completion` module or if it has been deprecated, you may need to modify your code to work with the available modules in the `mistralai` package. You can look for equivalent functionality under other module paths or newer classes.

   - **Search for `ChatMessage` in the Codebase**: If you're trying to use the `ChatMessage` class, it might have been moved to another module or replaced by a different class in newer versions of the library.
     You can search for `ChatMessage` in the installed `mistralai` package:
     ```bash
     grep -r "ChatMessage" <path_to_mistralai>
     ```
     This will show where `ChatMessage` is defined in the current package.

#### 5. **Use a Virtual Environment to Isolate Dependencies**
   If there are potential conflicts with other libraries or previous installations of `mistralai`, try installing it in a clean Python virtual environment to isolate dependencies and test again:

   - Create a new virtual environment:
     ```bash
     python -m venv myenv
     source myenv/bin/activate  # On Linux/Mac
     ```

   - Install `mistralai` in the new environment:
     ```bash
     pip install mistralai
     ```

   - Then test again if the error persists in the isolated environment.

#### 6. **Check for Open Issues or Report Your Own**
   Since you've mentioned that this bug was reported before in issue [[#640](https://github.com/mistralai/mistralai/issues/640)](https://github.com/mistralai/mistralai/issues/640), it's possible that the maintainers are already aware of the issue, and there may be a fix or workaround suggested in the comments. Make sure to check that issue for any updates.

   If there is no solution yet, consider posting your own detailed bug report on GitHub:
   - Go to the [[Mistralai Issues page](https://github.com/mistralai/mistralai/issues)](https://github.com/mistralai/mistralai/issues) and submit a new issue with a description of your problem, including the error trace and steps to reproduce.

Let me know how these steps go, and if you need more assistance, feel free to ask!

**Comment by WahahaZeng** [comment]
@micedevai Thank you so much for the help.

I found this article (https://github.com/mistralai/client-python/blob/d14559af390123cbd2d923e1e05f780500ce5411/MIGRATION.md?plain=1#L78) and it solves my problem.

Based on this article, chat_completion.py is deprecated.

**Comment by micedevai** [comment]
@WahahaZeng, You're welcome! I'm glad the article helped solve your problem. It’s good to know that the `chat_completion.py` is deprecated according to the article. If you need further assistance with any updates or migrating your code, feel free to reach out.
