### ISSUE TITLE
python devika.py not working

### ISSUE THREAD

**Issue by Adele583** [stitionai/devika#73]
PS C:\Users\hacke\Downloads\devika> python devika.py
24.03.23 06:25:40: root: WARNING: Ollama server not running, please start the server to use models from Ollama.
24.03.23 06:25:56: root: INFO   : Booting up... This may take a few seconds
24.03.23 06:25:56: root: INFO   : Initializing Devika...
24.03.23 06:25:56: root: INFO   : Initializing Prerequisites Jobs...
24.03.23 06:25:56: root: INFO   : Loading sentence-transformer BERT models...
Traceback (most recent call last):
  File "C:\Users\hacke\Downloads\devika\devika.py", line 207, in <module>
    init_devika()
  File "C:\Users\hacke\Downloads\devika\src\init.py", line 28, in init_devika
    SentenceBert(prompt).extract_keywords()
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hacke\Downloads\devika\src\bert\sentence.py", line 6, in __init__
    self.kw_model = KeyBERT()
                    ^^^^^^^^^
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\keybert\_model.py", line 57, in __init__
    self.model = select_backend(model)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\keybert\backend\_utils.py", line 47, in select_backend
    from ._sentencetransformers import SentenceTransformerBackend
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\keybert\backend\_sentencetransformers.py", line 3, in <module>
    from sentence_transformers import SentenceTransformer
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\datasets\DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\__init__.py", line 4, in <module>
    from .throughput_benchmark import ThroughputBenchmark
  File "C:\Users\hacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\throughput_benchmark.py", line 2, in <module>
    import torch._C
ModuleNotFoundError: No module named 'torch._C'
<img width="960" alt="image" src="https://github.com/stitionai/devika/assets/155518351/ddb4ce69-2dc9-49d0-b460-38c2bd572031">

**Comment by Adele583** [comment]
anyone who can help will really be appreciated

**Comment by Adele583** [comment]
l tried pip install torch._C and get this:
![image](https://github.com/stitionai/devika/assets/155518351/afb99b03-1582-4378-a148-221dbd512eb5)

**Comment by Adele583** [comment]
> did you activate python venv? did you try reinstalling pytorch `pip install torch`

no l never activated python venv

**Comment by Adele583** [comment]
please how do l do it

**Comment by bugthug404** [comment]
you do it by python uv package
command is `uv venv`
or
go through the installation process step by step https://github.com/stitionai/devika/blob/main/README.md

**Comment by Adele583** [comment]
thank you bugthug404

**Comment by 123vivekr** [comment]
hi @Adele583 is this resolved? do you still need help?

thanks @bugthug404 for the swift response!

**Comment by bautistaib** [comment]
Same issue here, I have tested it with the venv activated and without it. Have already tried the solution [here](https://github.com/nmilosev/pytorch-arm-builds/commit/8c811255de7d7e52268b204c7746bfb2be2e6893) and didn't work. If anyone could help it would be appreciated. I'm on a virtual machine with ubuntu 22.04 btw, idk if it's relevant

**Comment by javacaliente** [comment]
try 'python3 devika.py'
Also https://github.com/astral-sh/uv has a lot of useful info. 
After you 'uv venv' the virtual environment needs to be activated. The command is system dependent, but that link has it.
