### ISSUE TITLE
Route Logger error

### ISSUE THREAD

**Issue by PierrunoYT** [stitionai/devika#76]
I have some issue with the newest commits which causes some error with the route logger

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/stitionai/devika/assets/95778421/b651b8a8-9be1-468a-ae8f-208a7e2f3432)

**Comment by PierrunoYT** [comment]
I did this

open devika.py

remove these line wherever u find
@route_logger(logger)

but now I get this error

Token usage: 328
Exception in thread Thread-196 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pierr\devika\devika.py", line 50, in <lambda>
    target=lambda: Agent(base_model=base_model).execute(prompt, project_name)
  File "C:\Users\pierr\devika\src\agents\agent.py", line 264, in execute
    plan = self.planner.execute(prompt)
  File "C:\Users\pierr\devika\src\agents\planner\planner.py", line 70, in execute
    response = self.llm.inference(prompt)
  File "C:\Users\pierr\devika\src\llm\llm.py", line 56, in inference
    response = Claude().inference(self.model_id, prompt).strip()
  File "C:\Users\pierr\devika\src\llm\claude_client.py", line 14, in inference
    message = self.client.messages.create(
AttributeError: 'Anthropic' object has no attribute 'messages'
