### ISSUE TITLE
Handle ollama server not running bug

### ISSUE THREAD

**Issue by 123vivekr** [stitionai/devika#9]
Python crash stack traceback from @arajgor on Discord:

```
raceback (most recent call last):
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_transports\default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpcore\_sync\connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\D drive\Python\Main Projects\devika\devika.py", line 16, in <module>
    from src.agents import Agent
  File "D:\D drive\Python\Main Projects\devika\src\agents\__init__.py", line 1, in <module>
    from .agent import Agent
  File "D:\D drive\Python\Main Projects\devika\src\agents\agent.py", line 1, in <module>
    from .planner import Planner
  File "D:\D drive\Python\Main Projects\devika\src\agents\planner\__init__.py", line 1, in <module>
    from .planner import Planner
  File "D:\D drive\Python\Main Projects\devika\src\agents\planner\planner.py", line 3, in <module>
    from src.llm import LLM
  File "D:\D drive\Python\Main Projects\devika\src\llm\__init__.py", line 1, in <module>
    from .llm import LLM, TOKEN_USAGE
  File "D:\D drive\Python\Main Projects\devika\src\llm\llm.py", line 17, in <module>
    class Model(Enum):
  File "D:\D drive\Python\Main Projects\devika\src\llm\llm.py", line 25, in Model
    for model in ollama.list()["models"]:
                 ^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\ollama\_client.py", line 328, in list
    return self._request('GET', '/api/tags').json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\ollama\_client.py", line 68, in _request
    response = self._client.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_transports\default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\D drive\Python\Main Projects\devika\venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it
```

The ollama client module in devika\src\llm\llm.py is trying to reach ollama server, but its not running. This is a bug and should be handled properly.

**Comment by dongle132** [comment]
THX alot ... same problem here =)

**Comment by wrapss** [comment]
Atm ollama need to be on ur local machine, for change this edit ollama_client.py in src/llm folder : 

```
import ollama

HOST = 'http://10.33.1.130:11434'

class Ollama:
    @staticmethod
    def list_models():
        client = ollama.Client(host=HOST)
        return client.list()["models"]

    @staticmethod
    def inference(model_id: str, prompt: str) -> str:
        client = ollama.Client(host=HOST)
        response = client.chat(
            model=model_id,
            messages=[
                {
                    'role': 'user',
                    'content': prompt.strip(),
                },
            ]
        )
        return response[0]['content']
```

**Comment by rohittp0** [comment]
Could probably fixed easily by adding a try-except.

**Comment by Adele583** [comment]
same here
